language: node_js
node_js:
- '4.9.1'
before_script:
- npm install -g gulp@4.0.0
script: gulp
notifications:
  slack:
    secure: DBUhlx0LZYUDEirEdNUnqd8PuXFWc1uSiYfAdbkWHinND8cUEiyCwGSlt6JZno0jjuMb9V4Juo1Nk8q3zTTVfhHRMfDKL85jOunENcEmzF9UgY7SWsaoBSTYq3jElCjeDdWlBP0fCJ4zECaAI1I+CqC85gy6KASqugnlWNI0XEFIwkaAcEpzdL1i4lHnlh/GE85v9pL0wVJKD4767ye9ftEcPipr4efPR2+gW6nDSuRs6ZN6NtmibzSpwWc32iqUl9uYnVQ75lmV34t27eo/P9JyUiJ2Gk4pzu1R/nyRk7q3mc6ZIQNxMmorKDWHRAgN4AX1X2yFH49lmhH17/0lv6Vjy3dL4M87tMgMRuaWjh6QHLR8DZxAIo3IbLZaWDGEhBR5ardfICUHQwT7M94DFEvowZPAiJOkbA7/Ri6Tgsn542vFQMkrcFtE18Vz+8W+t8zHmhYwK2d0igh/6AA3QFiRsIt4CqWKgrJnJa2ogMCOUxglyjiE76hls9og1n+UZfjbbDizk6tsmwqmJcDgcgnlrMxWptXgkqOjgBf2VfDp5Sx2fJGs/Yo9NIVKG2ua7nZS+liWGyhjyJODyjdejbLimGYx1wv8s/HRKYPJgoLTFEf9Kol+rZ0OYLnS38iZo0mofTatRZ8mxlKaU7RNk+34XqMSto/F5F2YJN86mTQ=
